//Extension Constants
export const CREATE_EXTENSION = 'CREATE_EXTENSION';
export const UPDATE_EXTENSION = 'UPDATE_EXTENSION';
export const DELETE_EXTENSION = 'DELETE_EXTENSION';
export const GET_ALL_EXTENSIONS = 'GET_ALL_EXTENSIONS';
export const SEARCH_EXTENSIONS = 'SEARCH_EXTENSIONS';