//Site Constants
export const CREATE_TABLEDAY = 'CREATE_TABLEDAY';
export const UPDATE_TABLEDAY = 'UPDATE_TABLEDAY';
export const DELETE_TABLEDAY = 'DELETE_TABLEDAY';
export const GET_ALL_TABLEDAYS = 'GET_ALL_TABLEDAYS';
export const SEARCH_TABLEDAYS = 'SEARCH_TABLEDAYS';