//Ticket Constants
export const CREATE_TICKETHTML = 'CREATE_TICKETHTML';
export const UPDATE_TICKETHTML = 'UPDATE_TICKETHTML';
export const CHANGE_TICKETHTML_STATUS = 'CHANGE_TICKETHTML_STATUS';
export const DELETE_TICKETHTML = 'DELETE_TICKETHTML';
export const GET_ALL_TICKETHTMLS = 'GET_ALL_TICKETHTMLS';
export const SEARCH_TICKETHTMLS = 'SEARCH_TICKETHTMLS';