//Ticket Constants
export const CREATE_TICKET = 'CREATE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const CHANGE_TICKET_STATUS = 'CHANGE_TICKET_STATUS';
export const CHANGE_TICKET_ASSIGNED = 'CHANGE_TICKET_ASSIGNED';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const SEARCH_TICKETS = 'SEARCH_TICKETS';