//Site Constants
export const CREATE_TIMETABLE = 'CREATE_TIMETABLE';
export const UPDATE_TIMETABLE = 'UPDATE_TIMETABLE';
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE';
export const GET_ALL_TIMETABLES = 'GET_ALL_TIMETABLES';
export const SEARCH_TIMETABLES = 'SEARCH_TIMETABLES';